color0 #51443e
color1 #ffb4ab
color2 #f7b998
color3 #e1c0b0
color4 #cec98b
color5 #f7b998
color6 #e1c0b0
color7 #ebe0dc
color8 #9e8d85
color9 #ffb4ab
color10 #f7b998
color11 #e1c0b0
color12 #cec98b
color13 #f7b998
color14 #e1c0b0
color15 #ebe0dc

cursor                #ebe0dc
cursor_text_color     #000000
background            #000000
foreground            #ebe0dc
selection_foreground  #d6c3ba
selection_background  #51443e
active_border_color   #f7b998
inactive_border_color #433731
url_color             #f7b998

active_tab_foreground   #4c2610
active_tab_background   #f7b998
inactive_tab_foreground #d6c3ba
inactive_tab_background #433731
cursor_trail_color      #d6c3ba
